config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :baskets do 
    resources :bookings, only: %i[new create]
  end

  get "/dashboard", to: "pages#dashboard"

  resources :bookings do 
    member do
      post :accept
      post :decline
      post :cancel
    end
  end
end

app/models/basket.rb
class Basket < ApplicationRecord
  belongs_to :user
  has_many :bookings
  
  def self.search(search)
    where("name LIKE ?", "%#{search}%")
  end
end

app/models/booking.rb
class Booking < ApplicationRecord
  STATUS = %w[attente acceptée declinée annulée]

  belongs_to :user
  belongs_to :basket

  validates :status, inclusion: { in: Booking::STATUS }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :baskets
  has_many :bookings
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # Ici on ressort la liste des bookings faite à mes baskets
  has_many :requested_bookings, through: :baskets, source: :bookings

  # Ici on ressort la liste des Jordans que j'ai loué moi
  has_many :rented_jordans, through: :bookings, source: :basket
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    attributes = %i[first_name last_name email password password_confirmation]
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: attributes)

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: attributes)
  end
end

app/controllers/baskets_controller.rb
class BasketsController < ApplicationController
  before_action :set_basket, only: %i[edit show destroy update]

  def index
    if params[:query].present?
      @baskets = Basket.where("name ILIKE ?", "%#{params[:query]}%")
    else
      @baskets = Basket.all
    end
  end
  # def index
  #   @baskets = Basket.all
  # end

  def show
    @booking = Booking.new
  end

  def new
    @basket = Basket.new
  end

  def create
    @basket = Basket.new(params_basket)
    @basket.user = current_user
    @basket.image = params[:image]
    if @basket.save

      redirect_to basket_path(@basket)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    @basket.update(params_basket)
    redirect_to basket_path(@basket)
  end

  def destroy
    @basket.destroy
    redirect_to baskets_path, status: :see_other
  end

  private

  def set_basket
    @basket = Basket.find(params[:id])
  end

  def params_basket
    params.require(:basket)
          .permit(:name, :size, :description, :price_per_day, :image)
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @basket = Basket.find(params[:basket_id])
    @booking = Booking.new
  end

  def create
    @basket = Basket.find(params[:basket_id])
    @booking = Booking.new(bookings_params)
    @booking.basket = @basket
    @booking.user = current_user
    @booking.status = "attente"
    if @booking.save
      redirect_to dashboard_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def accept
    @booking = Booking.find(params[:id])
    @booking.update(status: "accepted")
    redirect_to dashboard_path if @booking.save
  end

  def decline
    @booking = Booking.find(params[:id])
    @booking.update(status: "declined")
    redirect_to dashboard_path if @booking.save
  end

  def cancel
    @booking = Booking.find(params[:id])
    @booking.update(status: "canceled")
    redirect_to dashboard_path if @booking.save
  end

  private

  def bookings_params
    params.require(:booking).permit(:start_date, :end_date)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    # skip_before_action :authenticate_user!, only: :home
  def home
    @baskets = Basket.all
  end

  def search
    @baskets = Basket.all
    if params[:search]
    @baskets = Basket.search(params[:search]).order("created_at DESC")
    else
    @books = Basket.all.order('created_at DESC')
    end

    def dashboard
      
    end
  end
end

app/views/baskets/_form.html.erb
<link rel="stylesheet" type="text/css" href="_form.css">

<div class ="form_style">
  <%= simple_form_for @basket do |f| %>
    <%= f.input :name,label: 'Nom de la paire ', placeholder: 'Ex: Jordan 3' %>
    <%= f.input :description,label: 'Description',  placeholder: 'Une description de ta paire !' %>
    <%= f.input :size, label: 'Taille', placeholder: 'La taille de cette paire' %>
    <%= f.input :price_per_day,label: 'Prix par jour de location', placeholder: "Ton prix par jour c'est ici !" %>
    <%# <%= f.input :image, label: 'Ta photo', placeholder: 'Envoie une photo' %> 
    <div class="mb-3 string optional basket_photo">
    <label class="form-label string optional" for="basket_price_per_day">Ta photo</label>
    <input class="form-control string optional" placeholder="Envoie une photo" type="text" name="image"></div>
    <%= f.submit class:"button_style"%>
    <%# <i class="fa-solid fa-basketball"></i> %>
  <% end %>
</div>

app/views/baskets/edit.html.erb
<div class="d-flex justify-content-center">
  <div class="card-trip mt-5 p-3">
	<h2 class="d-flex justify-content-center">page edit basket</h2>
	<%= render 'form' ,basket: @basket %>
  </div>
</div>

app/views/baskets/index.html.erb
<div class="container">
    <h3 class="text-center mt-3">
      All Jordans
    </h3>
    <div class="row justify-content-center">
    <% @baskets.each do |basket| %>
     <div class="card col-4 my-2 card_category">
      <img class="card-img-top" src="<%= basket.image %>" alt="Card image cap">
        <div class="card-body" data-turbo="false">
          <h5 class="card-title"><%= link_to basket.name, basket_path(basket)  %></h5>
          <h5 class="card-title"><%= basket.price_per_day  %> € / jour </h5>
          <p class="card-text"></p>
        </div>
      </div>
    <% end %>
  </div>
  </div>

app/views/baskets/new.html.erb
<div class="d-flex justify-content-center">
  <div class="card-trip mt-5 p-3">
    <h1 class="d-flex justify-content-center form_title_style"> Propose une paire !</h1>
    <%= render 'form' ,basket: @basket %>
  </div>
</div>

app/views/baskets/show.html.erb
<div class="container">
  <div class="d-flex justify-content-center">
  <div class="card-trip mt-5 pb-3">
    <img src="<%= @basket.image %>" />
    <div class="card-trip-infos">
      <div>
        <h2><%= @basket.name%> - Size : <%= @basket.size%> -	Price : <%= @basket.price_per_day %>€/day</h2>
        <p>Description : <%= @basket.description%></p>
        <h2></h2>
      </div>
      <!--<img src="https://kitt.lewagon.com/placeholder/users/krokrob" class="card-trip-user avatar-bordered" />-->
    </div>

    <div class="d-flex justify-content-center mb-2">
      <%#= link_to "edit my jordan", edit_basket_path(@basket), class: "btn btn-gradient me-2" %>
      <%#= link_to "Delete",basket_path(@basket) , class: "btn btn-danger me-3" , data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
      <%= link_to "Back all jordans", baskets_path, class: "btn btn-gradient me-3" %>
      <%# <%= link_to "Book this jordan", new_basket_booking_path(@basket),  class: "btn btn-danger me-3"%>
    </div>

    <div>
      <%= render "bookings/form" %>
    </div>
</div>
  

app/views/bookings/_form.html.erb
<%= simple_form_for([@basket, @booking]) do |f| %>
	<%= f.input :start_date, as: :string, label: 'Choisissez une date de début :', :input_html => { :class => 'datepicker', :placeholder => "Cliquez ici pour choisir" } %>
	<%= f.input :end_date, as: :string, label: 'Choisissez une date de fin :', :input_html => { :class => 'datepicker', :placeholder => "Cliquez ici pour choisir"  } %> 
	<div class="d-flex"><%= f.submit "Validez une demande de location", class:"btn btn-info bookings-submit"%></div>
<% end %>
<script>
document.addEventListener("turbo:load", () => {
  flatpickr(".datepicker", {
    altInput: true,
    altFormat: "F j, Y",
    dateFormat: "Y-m-d",
  });
});
</script>
<style>
.bookings-submit {
	margin: 0 auto;
}
</style>

app/views/bookings/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Bookings index</h1>

<div id="bookings">
  <% @bookings.each do |booking| %>
    <%= render booking %>
    <p>
      <%= link_to "Show this booking", booking %>
    </p>
  <% end %>
</div>

<%= link_to "New booking", new_booking_path %>

app/views/bookings/new.html.erb
<%= simple_form_for([@basket, @booking]) do |f| %>
	<%= f.input :start_date %>
	<%= f.input :end_date %> 
	<%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>My Jordans!</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  <!-- <link href="https://unpkg.com/tailwindcss@^2.0/dist/tailwind.min.css"
      rel="stylesheet"/>
  </head> -->

  <body>
    <%= render "components/navbar" %>
      <div class="page-wrapper">
        <%= yield %>
      </div>
    <%= render "components/footer" %>
  </body>
</html>
<style>
  .page-wrapper {
    min-height: 100vh;
    display: flex;
    flex-direction: column;
    <%# justify-content: center; %>
    <%# align-items: center; %>
  }
</style>

app/views/pages/dashboard.html.erb
<div class="container">
  <div class="main">
	<div class="navbar navbar-expand-sm navbar-light navbar-lewagon-dashboard">
     <div class="container-fluid dashboard-links">
		<ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
		  <li class="nav-item " role="presentation">
		    <button class="nav-link active" id="pills-dasb-tab" data-bs-toggle="pill" data-bs-target="#pills-dash" type="button" role="tab" aria-controls="pills-profile" aria-selected="false">Mes jordans</button>
		  </li>
		  <li class="nav-item" role="presentation">
		    <button class="nav-link" id="pills-profile-tab" data-bs-toggle="pill" data-bs-target="#pills-profile" type="button" role="tab" aria-controls="pills-profile" aria-selected="false">Mes locations</button>
		  </li>
		  <li class="nav-item" role="presentation">
		    <button class="nav-link" id="pills-contact-tab" data-bs-toggle="pill" data-bs-target="#pills-contact" type="button" role="tab" aria-controls="pills-contact" aria-selected="false">Mes demandes</button>
		  </li>
		  <li class="nav-item" role="presentation">
		    <button class="nav-link" id="pills-contact-tab" data-bs-toggle="pill" data-bs-target="#pills-last" type="button" role="tab" aria-controls="pills-last" aria-selected="false">Mes Baskets louées</button>
		  </li>
		</ul>
	   </div>
	 </div>
	 <div class="tab-content" id="pills-tabContent">
	   <div class="tab-pane fade show active" id="pills-dash" role="tabpanel" aria-labelledby="pills-profile-tab" tabindex="0">
			<!-- Ici on affiche mes baskets -->
			<div class="row dashboard mb-3">
				<% current_user.baskets.each do |basket|%>
				<div class="flash">
					<div class="col-3">
						<%= basket.name %>
					</div>
					<div class="col-4 d-flex justify-content-center">
						<img class="card-img-top dashboard" src="<%= basket.image %>" alt="Card image cap">
					</div>
					<div class="col-3">
						<h5>Taille : <%= basket.size %></h5>
					</div>
					<div class="col-3">
						<h5><%= basket.price_per_day %> €/jour</h5>
					</div>
				</div>
			   <% end %>
		    </div>
        </div>
		<div class="tab-pane fade" id="pills-profile" role="tabpanel" aria-labelledby="pills-profile-tab" tabindex="0">
		  	
				<!-- Ici on affiche les demandes pour mes baskets -->
				<div class="row dashboard mb-3">
					<% current_user.requested_bookings.each do |booking|%>
					<div class="flash">
						<div class="col-2">
						<%= booking.basket.name%>
						</div>
						<div class="col-2 d-flex justify-content-center">
						 <img class="card-img-top dashboard" src="<%= booking.basket.image %>" alt="Card image cap">
						</div>
						<div class="col-2">
						<%= booking.status%>
						<!-- Ici on affiche le bouton seulement si la reservation n'est pas déjà accepted -->
						</div>
						<div class="col-2">
						<% if booking.status != "acceptée" %>
						  <%= button_to "Accepter la réservation", accept_booking_path(booking), data: { turbo_method: :post } , class:"btn btn-success"%>
						 <% end %>
						</div>
						<div class="col-2">
					  <!-- Ici on affiche le bouton seulement si la reservation n'est pas déjà declined -->
						<% if booking.status != "acceptée" %>
					  <%= button_to "Décliner la réservation", decline_booking_path(booking), data: { turbo_method: :post }, class:"btn btn-primary"%>
					  <% end %>
					</div>
					</div>
					<% end %>
			    </div>
		     </div>
		     <div class="tab-pane fade" id="pills-contact" role="tabpanel" aria-labelledby="pills-profile-tab" tabindex="0">
			    <div class="row dashboard mb-3">
				<!-- Ici on affiche les demandes que j'ai faites -->
				<% current_user.bookings.each do |booking|%>
				   <div class="flash">
				   	<div class="col-2">
					  <h6>Demandé par <%= booking.user.first_name %></h6>
					</div>
				   	<div class="col-2">	
					  <%= booking.basket.name%>
				   	</div>
				   	<div class="col-3 d-flex justify-content-center">
						 <img class="card-img-top dashboard" src="<%= booking.basket.image %>" alt="Card image cap">
					</div>
				   	<div class="col-2">
					  <%= booking.status %>
				   	</div>
				   	<div class="col-3">
				   		<%#= booking.start_date %>
						<%#= booking.end_date %>
					  <!-- Ici on affiche le bouton seulement si la reservation n'est pas déjà canceled -->
					  <% if booking.status != "annulée" %>
					  <%#= button_to "Réponse en réservation", cancel_booking_path(booking), data: { turbo_method: :post }, class:"btn btn-danger"%>
					  <% end %>
					</div>

				   </div>
				<% end %>
				  </div> 
				</div>
              </div>
               <div class="tab-pane fade" id="pills-last" role="tabpanel" aria-labelledby="pills-profile-tab" tabindex="0">
			     <div class="row dashboard mb-3">
				<!-- Ici on affiche les baskets que j'ai déjà loué -->
				<% current_user.rented_jordans.each do |basket|%>
					<div class="flash">
						<div class="col-2">
						  <%= basket.name%>
						</div>
						<div class="col-3 d-flex justify-content-center">
						 <img class="card-img-top dashboard" src="<%= basket.image %>" alt="Card image cap">
					    </div>
						<div class="col-3">
						<h4>Loué a : <%= basket.user.first_name %></h4>
						</div>
					</div>
				<% end %>
			     </div>
			    </div>
			</div>
     </div>
</div>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('cover-jordan.jpg')";>
  <div class="container">

    <h1>Boutique de baskets Jordan</h1>
    <p>Boutique en ligne de location de baskets air Jordan </p>

  <%# <div class="input-group d-flex justify-content-center" style="width: 80%"> %>
    <%= form_with url: baskets_path, method: :get, class: "d-flex search-bar" do %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control",
        placeholder: "Trouve ta basket"
      %>
      <%= submit_tag "Recherche", class: "btn btn-secondary" %>
    <% end %>

</div>
  </div>
  <div class="container mt-5">
    <div>
    <div class="row justify-content-center">
    <% @baskets.each do |basket| %>
     <div class="card col-4 my-2 card_category">
      <img class="card-img-top" src="<%= basket.image %>" alt="Card image cap">
        <div class="card-body" data-turbo="false">
          <h5 class="card-title"><%= link_to basket.name, basket_path(basket)  %></h5>
          <h5 class="card-title"><%= basket.price_per_day  %> € / jour </h5>
          <p class="card-text"></p>
        </div>
      </div>
    <% end %>
  </div>
  </div>
</div>